### ISSUE TITLE
Summary and vision

### ISSUE THREAD

**Issue by Von-Seth** [COMP-4350-Group-8/admin#10]
Provide a written project Summary and vision.

Items:
  - [x] Core features - at least,
    - [x]  4 functional features
    - [x]  1 non-functional feature related to capacity of the application (e.g., can response 100 users with 1000 requests per minute concurrently)
  - [x] Key features
    - [x] Key User Stories for key features 
      - First Key User Stories are must-haves, you may/will add more users stories, and maybe features, later in the project)
    - [x] Include acceptance criteria
      - [using this as a template](https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important) which is close to an acceptance test, but before any interfaces are made - it’s a desired acceptance test)

**Comment by OwenHny** [comment]
Added to shared google doc
