### ISSUE TITLE
Schedule First Meeting with Project Owner

### ISSUE THREAD

**Issue by Von-Seth** [COMP-4350-Group-8/admin#18]
Description: Schedule a meeting with PO to pitch them on the idea. We will work through our worksheet and the PO will grade us on the rubric

Meeting:
- Date: 2024-09-27 at 13:30-TBD
- Duration: TBD
  - (Read comments)
- Location: TBD (in-person)
  - (The first meeting will be in-person, unless not possible)

> [!IMPORTANT]
> Confirm all members are CC in any email to and from the PO

Tasks:
- [x] Email PO to schedule the meeting
  - [x] Initial email: _(Send draft in comments, and have minimum 1 member review - prior to sending)_
    - [x] Introduce our group & project
    - [x] Propose the meeting date
  - [x] Determine location & book room
  - [x] Confirm meeting
- [x] Send a message in #meeting-updates channel with meeting information (once meeting info is determined)

**Comment by nurlanua** [comment]
Messed up with the dates:  Instead of 2024-09-27 at 13:30  to 2024-09-23 at 13:30
Messed up with the CC: did not include anyone in CC section from the very beginning and did not confirm with at least 1 member prior to sending
Location: Engineering Room 362B
Meeting will be held on Microsoft Teams
