### ISSUE TITLE
Presentation Proposal

### ISSUE THREAD

**Issue by Von-Seth** [COMP-4350-Group-8/admin#5]
Presentation Proposal (elevator pitch)
- Due: 2024-09-20 at 11:30
- Format: in-person presentation 

Description:\
...present their proposed project in the class...

Items:
- [x] Important presentation points:
  - [x] What is your application?
  - [x] Why do people want to use it?
  - [x]  What are the key features you’ll deliver?
  - [x] What technology stack are you planning on using? (You are not committed to this decision.)
    - [x] Show a very simplified and high level architecture diagram showing your plan
    - [x] Highlight the different technologies 
      - why you chose them
      - how they will work together
- [x] Name of product
- [x] Keep presentation time under 5 minutes

**Comment by OwenHny** [comment]
Presentation completed, slides available in shared google folder
